UATUrl = https://app-dev.poweradspy.com/amember/member
TestUrl =https://app-dev.poweradspy.com/amember/member
UserName= palladiumyearly
Password= palladiumyearly
Browser = chrome
Browser1=firefox
chromepath=Drivers//chromedriver.exe
edgepath=Drivers/msedgedriver.exe
firefoxpath=Drivers//geckodriver.exe
operapath=Drivers//operadriver.exe

EcomPlatform=WooCommerce
VerfiyEcomPlatform=WooCommerce.png

MarketingPlatformBrand=Google Marketing Platform
platform=doubleclick

CallToAction=Apply Now
VerifyCallToAction=Apply Now

Leftmonthselect1=Jul
Leftyearselect1=2022

Rightmonthselect2=Jan
Rightyearselect2=2023

Country=India

country=Spain

Language=Hindi

gender=Male

MinAge=0
MaxAge=75

minlike=2000
maxlike=50000

minView=100
maxView=800

minComment=100
maxComment=2000

minDislike=1
maxDislike=10

EnterUrl=amazon

Enterkeyword=PAS

Enteradvertiser=Discount

